### ISSUE TITLE
theme engine

### ISSUE THREAD

**Issue by rai-roshan** [rai-roshan/react-sorting-visualizer#6]
implement light and dark mode for the whole application.

**Comment by AbdirahimAhmedNor** [comment]
I can do that for you. `Please assign me`.

**Comment by rai-roshan** [comment]
I will be happy to assign you this , but before that can you explain the approach that you are thinking to go with .

**Comment by AbdirahimAhmedNor** [comment]
The way I will approach is that I will bring an icon, if the application in **light mode** the icon will look like a *sun* if it is **dark mode**  it will look like a *moon*. So whenever the user taps it will change. The icon will be displayed before the `sorting option button`  and it will be stored in the cookies. thank you

**Comment by rai-roshan** [comment]
> The way I will approach is that I will bring an icon, if the application in **light mode** the icon will look like a _sun_ if it is **dark mode** it will look like a _moon_. So whenever the user taps it will change. The icon will be displayed before the `sorting option button` and it will be stored in the cookies. thank you

yeah a good idea but what i was asking is how the programatic approch will be , are you gonna use react context or state to toggle between the light/dark modes , and how you gonna apply the theme color to every element , are you planning to use inbuilt react style attribute , or will define css classes or use css variables .

**Comment by AbdirahimAhmedNor** [comment]
I will use react-redux that is the I am familiar with  instead of react context, I am planning to go css variables

**Comment by rai-roshan** [comment]
> I will use react-redux that is the one I am familiar with instead of react context, I am planning to go css variables

yeah redux can be used but that will be unnecessary for something simple as toggling theme , we can go with using simple state , i dont want to use any additional library , and also want to avoid unnecessary re-rendering of components , so keeping those things in mind you can think for some simple and efficient approach, go through the code and its structure once , that may help you.

**Comment by AbdirahimAhmedNor** [comment]
I have no problem using react-context either

**Comment by AbdirahimAhmedNor** [comment]
> > I will use react-redux that is the one I am familiar with instead of react context, I am planning to go css variables
> 
> yeah redux can be used but that will be unnecessary for something simple as toggling theme , we can go with using simple state , i dont want to use any additional library , and also want to avoid unnecessary re-rendering of components , so keeping those things in mind you can think for some simple and efficient approach, go through the code and its structure once , that may help you.

I have understood your point, I have no problem using react-context either.

**Comment by rai-roshan** [comment]
> > > I will use react-redux that is the one I am familiar with instead of react context, I am planning to go css variables
> > 
> > 
> > yeah redux can be used but that will be unnecessary for something simple as toggling theme , we can go with using simple state , i dont want to use any additional library , and also want to avoid unnecessary re-rendering of components , so keeping those things in mind you can think for some simple and efficient approach, go through the code and its structure once , that may help you.
> 
> I have understood your point, I have no problem using react-context either.

ok you can go ahead with the implementation , l am assigning you this issue.

**Comment by AbdirahimAhmedNor** [comment]
I appreciate that
